# Generated by Django 5.1.7 on 2025-06-04 17:35

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        max_length=150, verbose_name="Медицинская компания"
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        max_length=2000, verbose_name="Описание медицинской компании"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Электронная почта компании"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        validators=[users.validators.phone_number_validator],
                        verbose_name="телефонный номер компании",
                    ),
                ),
                (
                    "history",
                    models.TextField(max_length=2000, verbose_name="История компании"),
                ),
                (
                    "values",
                    models.TextField(max_length=2000, verbose_name="Миссия и ценности"),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Адрес клиники"),
                ),
                (
                    "map_address",
                    models.URLField(
                        max_length=2000, verbose_name="Карта проезда(ссылка iframe)"
                    ),
                ),
            ],
            options={
                "verbose_name": "компания",
                "verbose_name_plural": "компании",
            },
        ),
    ]
