# Generated by Django 5.1.7 on 2025-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppointmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ap_date", models.DateField(verbose_name="дата записи.")),
                ("ap_time", models.TimeField(verbose_name="врямя записи.")),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
            },
        ),
        migrations.CreateModel(
            name="MedServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="название медицинской услуги"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=2000, verbose_name="описание медицинской услуги"
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="стоимость"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="clinic",
                        verbose_name="иллюстрация услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская услуга",
                "verbose_name_plural": "Медицинские услуги",
            },
        ),
        migrations.CreateModel(
            name="MedStaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="Ф.И.О медицинского специалиста."
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("Врач", "Врач"), ("Медсестра", "Медсестра")],
                        max_length=20,
                        verbose_name="медицинская должность",
                    ),
                ),
                (
                    "speciality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("гинеколог", "гинеколог"),
                            ("кардиолог", "кардиолог"),
                            ("нейрохирург", "нейрохирург"),
                            ("невролог", "невролог"),
                            ("эндокринолог", "эндокринолог"),
                            ("терапевт", "терапевт"),
                            ("онколог", "онколог"),
                            ("ревматолог", "ревматолог"),
                            ("флеболог", "флеболог"),
                            ("мамолог", "мамолог"),
                            ("рентгенолог", "рентгенолог"),
                        ],
                        max_length=20,
                        verbose_name="специальность",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="clinic", verbose_name="фото специалиста"
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинский работник",
                "verbose_name_plural": "Медицинские работники",
            },
        ),
        migrations.CreateModel(
            name="ResultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_date",
                    models.DateField(verbose_name="дата результата медуслуги"),
                ),
                (
                    "result",
                    models.TextField(
                        max_length=5000,
                        verbose_name="эпикриз по результатам медицинской процедуры",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат",
                "verbose_name_plural": "результаты",
            },
        ),
    ]
