# Generated by Django 5.1.7 on 2025-06-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentmodel",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пациент",
            ),
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="med_serv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.medservicemodel",
                verbose_name="медицинская услуга",
            ),
        ),
        migrations.AddField(
            model_name="medservicemodel",
            name="med_spec",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clinic.medstaffmodel",
                verbose_name="назначенный медицинский специалист",
            ),
        ),
        migrations.AddField(
            model_name="resultmodel",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clinic.appointmentmodel",
                verbose_name="назнечение на процедуру",
            ),
        ),
        migrations.AddField(
            model_name="resultmodel",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пациент",
            ),
        ),
    ]
