# Generated by Django 5.1.7 on 2025-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medstaffmodel",
            name="education",
            field=models.TextField(blank=True, verbose_name="образование"),
        ),
    ]
