# Generated by Django 5.1.7 on 2025-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medstaffmodel",
            name="speciality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("гинеколог", "гинеколог"),
                    ("кардиолог", "кардиолог"),
                    ("нейрохирург", "нейрохирург"),
                    ("невролог", "невролог"),
                    ("эндокринолог", "эндокринолог"),
                    ("терапевт", "терапевт"),
                    ("онколог", "онколог"),
                    ("ревматолог", "ревматолог"),
                    ("флеболог", "флеболог"),
                    ("мамолог", "мамолог"),
                    ("рентгенолог", "рентгенолог"),
                ],
                verbose_name="специальность",
            ),
        ),
    ]
