# Generated by Django 5.1.7 on 2025-05-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_alter_medstaffmodel_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="medstaffmodel",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clinic",
                verbose_name="фото специалиста",
            ),
        ),
    ]
